/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o usuário autenticado
         * @description Retorna informações do usuário extraídas do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUser"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/profile/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o perfil do usuário autenticado
         * @description Retorna atributos de identidade e institucionais (CPF, NomeSocial) extraídos do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUserProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/_smoke/cache/{key}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Smoke E2E — Cache probe
         * @description Faz SET/GET de uma chave temporária no Redis com TTL 5min para validar conectividade. Restrito a usuários com role admin.
         */
        readonly get: operations["smokeCacheProbe"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/_smoke/messaging/publish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Smoke E2E — Messaging publish
         * @description Publica um SmokePingMessage via Wolverine outbox para validar persistência + transport (PG queue durável). O handler em Infrastructure.Core registra log do round-trip. Restrito a usuários com role admin.
         */
        readonly post: operations["smokeMessagingPublish"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cep/{cep}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly cep: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["CepResolvidoDto"];
                        readonly "application/json": components["schemas"]["CepResolvidoDto"];
                        readonly "text/json": components["schemas"]["CepResolvidoDto"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades/{codigoIbge}/distritos": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiCidadesCodigoIbgeDistritosGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path: {
                    readonly codigoIbge: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["DistritoDto"][];
                        readonly "application/json": readonly components["schemas"]["DistritoDto"][];
                        readonly "text/json": readonly components["schemas"]["DistritoDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades/{codigoIbge}/bairros": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly q?: string;
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiCidadesCodigoIbgeBairrosGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path: {
                    readonly codigoIbge: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["BairroDto"][];
                        readonly "application/json": readonly components["schemas"]["BairroDto"][];
                        readonly "text/json": readonly components["schemas"]["BairroDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades/{codigoIbge}/logradouros": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly q?: string;
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiCidadesCodigoIbgeLogradourosGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path: {
                    readonly codigoIbge: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["LogradouroResumoDto"][];
                        readonly "application/json": readonly components["schemas"]["LogradouroResumoDto"][];
                        readonly "text/json": readonly components["schemas"]["LogradouroResumoDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly uf?: string;
                    readonly q?: string;
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiCidadesGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["CidadeResumoDto"][];
                        readonly "application/json": readonly components["schemas"]["CidadeResumoDto"][];
                        readonly "text/json": readonly components["schemas"]["CidadeResumoDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades/{codigoIbge}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly codigoIbge: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["CidadeDetalheDto"];
                        readonly "application/json": components["schemas"]["CidadeDetalheDto"];
                        readonly "text/json": components["schemas"]["CidadeDetalheDto"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/estados": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiEstadosGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["EstadoDto"][];
                        readonly "application/json": readonly components["schemas"]["EstadoDto"][];
                        readonly "text/json": readonly components["schemas"]["EstadoDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/estados/{uf}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly uf: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["EstadoDto"];
                        readonly "application/json": components["schemas"]["EstadoDto"];
                        readonly "text/json": components["schemas"]["EstadoDto"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/geo/importacoes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["DispararImportacaoRequest"];
                    readonly "text/json": components["schemas"]["DispararImportacaoRequest"];
                    readonly "application/*+json": components["schemas"]["DispararImportacaoRequest"];
                };
            };
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ImportacaoGeoDto"];
                        readonly "application/json": components["schemas"]["ImportacaoGeoDto"];
                        readonly "text/json": components["schemas"]["ImportacaoGeoDto"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Service Unavailable */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/geo/importacoes/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ImportacaoGeoDto"];
                        readonly "application/json": components["schemas"]["ImportacaoGeoDto"];
                        readonly "text/json": components["schemas"]["ImportacaoGeoDto"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/cidades/proximas": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query: {
                    readonly lat: number | string;
                    readonly long: number | string;
                    readonly raioKm: number | string;
                    readonly limit?: number | string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["CidadeProximaDto"][];
                        readonly "application/json": readonly components["schemas"]["CidadeProximaDto"][];
                        readonly "text/json": readonly components["schemas"]["CidadeProximaDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/logradouros/proximos": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query: {
                    readonly lat: number | string;
                    readonly long: number | string;
                    readonly raioKm: number | string;
                    readonly limit?: number | string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["LogradouroProximoDto"][];
                        readonly "application/json": readonly components["schemas"]["LogradouroProximoDto"][];
                        readonly "text/json": readonly components["schemas"]["LogradouroProximoDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AuthenticatedUserResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
        readonly BairroDto: {
            /** Format: uuid */
            readonly id: string;
            readonly nome: string;
            readonly uf: string;
            readonly cidadeCodigoIbge: string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly CepResolvidoDto: {
            readonly cep: string;
            readonly tipo: null | string;
            readonly logradouro: null | string;
            readonly complemento: null | string;
            readonly bairro: null | string;
            readonly distrito: null | string;
            readonly cidade: string;
            readonly codigoIbge: string;
            readonly uf: string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly nivelResolucao: string;
            readonly origem: string;
            readonly alternativos?: readonly components["schemas"]["LogradouroAlternativoDto"][];
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly CidadeDetalheDto: {
            /** Format: uuid */
            readonly id: string;
            readonly codigoIbge: string;
            readonly nome: string;
            readonly uf: string;
            readonly ddd: null | string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly mesorregiaoNome: null | string;
            readonly microrregiaoNome: null | string;
            readonly regiaoIntermediariaNome: null | string;
            readonly regiaoImediataNome: null | string;
            readonly indicador: null | components["schemas"]["CidadeIndicadorDto"];
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly CidadeIndicadorDto: {
            readonly gentilico: null | string;
            /** Format: double */
            readonly areaKm2: null | number | string;
            /** Format: int32 */
            readonly populacaoResidente: null | number | string;
            /** Format: double */
            readonly densidadeDemografica: null | number | string;
            /** Format: double */
            readonly idh: null | number | string;
            readonly aniversario: null | string;
        };
        readonly CidadeProximaDto: {
            /** Format: uuid */
            readonly id: string;
            readonly codigoIbge: string;
            readonly nome: string;
            readonly uf: string;
            /** Format: double */
            readonly latitude: number | string;
            /** Format: double */
            readonly longitude: number | string;
            /** Format: double */
            readonly distanciaKm: number | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly CidadeResumoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly codigoIbge: string;
            readonly nome: string;
            readonly uf: string;
            readonly ddd: null | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly DispararImportacaoRequest: {
            readonly versao: string;
        };
        readonly DistritoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly nome: string;
            readonly uf: string;
            readonly cidadeCodigoIbge: string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly EstadoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly uf: string;
            readonly nome: string;
            readonly regiao: null | string;
            readonly capital: null | string;
            readonly codigoIbge: null | string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly ImportacaoGeoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly versaoDataset: string;
            readonly status: string;
            /** Format: date-time */
            readonly iniciadoEm: string;
            /** Format: date-time */
            readonly concluidoEm: null | string;
            readonly disparadoPor: string;
            readonly mensagem: null | string;
            readonly relatorio: null | components["schemas"]["RelatorioImportacaoDto"];
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly LogradouroAlternativoDto: {
            readonly tipo: null | string;
            readonly logradouro: string;
            readonly bairro: null | string;
            readonly distrito: null | string;
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
        };
        readonly LogradouroProximoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly cep: string;
            readonly tipo: null | string;
            readonly nome: string;
            readonly cidadeNome: string;
            readonly cidadeCodigoIbge: string;
            readonly uf: string;
            /** Format: double */
            readonly latitude: number | string;
            /** Format: double */
            readonly longitude: number | string;
            /** Format: double */
            readonly distanciaKm: number | string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly LogradouroResumoDto: {
            /** Format: uuid */
            readonly id: string;
            readonly cep: string;
            readonly tipo: null | string;
            readonly nome: string;
            readonly nomeCompleto: null | string;
            readonly bairro: null | string;
            readonly cidadeCodigoIbge: string;
            readonly uf: string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
        readonly RelatorioImportacaoDto: {
            readonly versaoDataset: string;
            /** Format: int32 */
            readonly lidos: number | string;
            /** Format: int32 */
            readonly inseridos: number | string;
            /** Format: int32 */
            readonly atualizados: number | string;
            /** Format: int32 */
            readonly orfaos: number | string;
            /** Format: int32 */
            readonly degradados: number | string;
            readonly tabelas: readonly components["schemas"]["TabelaImportacaoDto"][];
        };
        readonly TabelaImportacaoDto: {
            readonly tabela: string;
            /** Format: int32 */
            readonly lidos: number | string;
            /** Format: int32 */
            readonly inseridos: number | string;
            /** Format: int32 */
            readonly atualizados: number | string;
            /** Format: int32 */
            readonly ignoradosSemChave: number | string;
            /** Format: int32 */
            readonly orfaos: number | string;
            /** Format: int32 */
            readonly duplicados: number | string;
            /** Format: int32 */
            readonly parsesDegradados: number | string;
            readonly amostras: readonly string[];
        };
        readonly UserProfileResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            /** @description CPF (apenas dígitos, sem formatação). PII — sempre mascarar em logs ('***.999.999-**', ADR-0011). */
            readonly cpf: null | string;
            readonly nomeSocial: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly GetAuthenticatedUser: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly GetAuthenticatedUserProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly smokeCacheProbe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly key: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly smokeMessagingPublish: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
export enum PathsApiCidadesCodigoIbgeDistritosGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiCidadesCodigoIbgeBairrosGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiCidadesCodigoIbgeLogradourosGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiCidadesGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiEstadosGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
