# Stage 1: Build
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json nx.json tsconfig.base.json ./
RUN npm ci
COPY . .
RUN npx nx build selecao --configuration=production

# Stage 2: Serve
FROM nginx:1.27-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/apps/selecao/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
