/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o usuário autenticado
         * @description Retorna informações do usuário extraídas do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUser"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/profile/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o perfil do usuário autenticado
         * @description Retorna atributos de identidade e institucionais (CPF, NomeSocial) extraídos do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUserProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/editais": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly AfterId?: string;
                    readonly Limit?: number | string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["EditalDto"][];
                        readonly "application/json": readonly components["schemas"]["EditalDto"][];
                        readonly "text/json": readonly components["schemas"]["EditalDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarEditalCommand"];
                    readonly "text/json": components["schemas"]["CriarEditalCommand"];
                    readonly "application/*+json": components["schemas"]["CriarEditalCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/editais/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["EditalDto"];
                        readonly "application/json": components["schemas"]["EditalDto"];
                        readonly "text/json": components["schemas"]["EditalDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/editais/{id}/publicar": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AuthenticatedUserResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
        readonly CriarEditalCommand: {
            /** Format: int32 */
            readonly numeroEdital: number | string;
            /** Format: int32 */
            readonly anoEdital: number | string;
            readonly titulo: string;
            readonly tipoProcesso: components["schemas"]["TipoProcesso"];
            /**
             * Format: int32
             * @default 1
             */
            readonly maximoOpcoesCurso: number | string;
        };
        readonly EditalDto: {
            /** Format: uuid */
            readonly id: string;
            readonly numeroEdital: string;
            readonly titulo: string;
            readonly tipoProcesso: string;
            readonly status: string;
            /** Format: int32 */
            readonly maximoOpcoesCurso: number | string;
            readonly bonusRegionalHabilitado: boolean;
            /** Format: date-time */
            readonly criadoEm: string;
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
        readonly TipoProcesso: number;
        readonly UserProfileResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            /** @description CPF (apenas dígitos, sem formatação). PII — sempre mascarar em logs ('***.***.***-XX', ADR-0011). */
            readonly cpf: null | string;
            readonly nomeSocial: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly GetAuthenticatedUser: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly GetAuthenticatedUserProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
