/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o usuário autenticado
         * @description Retorna informações do usuário extraídas do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUser"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/profile/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o perfil do usuário autenticado
         * @description Retorna atributos de identidade e institucionais (CPF, NomeSocial) extraídos do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUserProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/selecao/obrigatoriedades-legais": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly tipoEdital?: string;
                    readonly categoria?: components["schemas"]["CategoriaObrigatoriedade"];
                    readonly vigentes?: boolean;
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiSelecaoObrigatoriedadesLegaisGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["ObrigatoriedadeLegalDto"][];
                        readonly "application/json": readonly components["schemas"]["ObrigatoriedadeLegalDto"][];
                        readonly "text/json": readonly components["schemas"]["ObrigatoriedadeLegalDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/selecao/obrigatoriedades-legais/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ObrigatoriedadeLegalDto"];
                        readonly "application/json": components["schemas"]["ObrigatoriedadeLegalDto"];
                        readonly "text/json": components["schemas"]["ObrigatoriedadeLegalDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/selecao/admin/obrigatoriedades-legais": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarObrigatoriedadeLegalCommand"];
                    readonly "text/json": components["schemas"]["CriarObrigatoriedadeLegalCommand"];
                    readonly "application/*+json": components["schemas"]["CriarObrigatoriedadeLegalCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/selecao/admin/obrigatoriedades-legais/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["AtualizarObrigatoriedadeLegalCommand"];
                    readonly "text/json": components["schemas"]["AtualizarObrigatoriedadeLegalCommand"];
                    readonly "application/*+json": components["schemas"]["AtualizarObrigatoriedadeLegalCommand"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AtualizarObrigatoriedadeLegalCommand: {
            /** Format: uuid */
            readonly id: string;
            readonly tipoEditalCodigo: string;
            readonly categoria: components["schemas"]["CategoriaObrigatoriedade"];
            readonly regraCodigo: string;
            readonly predicado: components["schemas"]["PredicadoObrigatoriedade"];
            readonly descricaoHumana: string;
            readonly baseLegal: string;
            /** Format: date */
            readonly vigenciaInicio: string;
            /** Format: date */
            readonly vigenciaFim: null | string;
            readonly atoNormativoUrl: null | string;
            readonly portariaInternaCodigo: null | string;
        };
        readonly AuthenticatedUserResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
        /** @enum {string} */
        readonly CategoriaObrigatoriedade: CategoriaObrigatoriedade;
        readonly CriarObrigatoriedadeLegalCommand: {
            readonly tipoEditalCodigo: string;
            readonly categoria: components["schemas"]["CategoriaObrigatoriedade"];
            readonly regraCodigo: string;
            readonly predicado: components["schemas"]["PredicadoObrigatoriedade"];
            readonly descricaoHumana: string;
            readonly baseLegal: string;
            /** Format: date */
            readonly vigenciaInicio: string;
            /** Format: date */
            readonly vigenciaFim: null | string;
            readonly atoNormativoUrl: null | string;
            readonly portariaInternaCodigo: null | string;
        };
        readonly JsonElement: unknown;
        readonly ObrigatoriedadeLegalDto: {
            /** Format: uuid */
            readonly id: string;
            readonly tipoEditalCodigo: string;
            readonly categoria: components["schemas"]["CategoriaObrigatoriedade"];
            readonly regraCodigo: string;
            readonly predicado: components["schemas"]["PredicadoObrigatoriedade"];
            readonly descricaoHumana: string;
            readonly baseLegal: string;
            readonly atoNormativoUrl: null | string;
            readonly portariaInternaCodigo: null | string;
            /** Format: date */
            readonly vigenciaInicio: string;
            /** Format: date */
            readonly vigenciaFim: null | string;
            readonly hash: string;
            readonly isDeleted: boolean;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly PredicadoObrigatoriedade: components["schemas"]["PredicadoObrigatoriedadeEtapaObrigatoria"] | components["schemas"]["PredicadoObrigatoriedadeModalidadesMinimas"] | components["schemas"]["PredicadoObrigatoriedadeDesempateDeveIncluir"] | components["schemas"]["PredicadoObrigatoriedadeDocumentoObrigatorioParaModalidade"] | components["schemas"]["PredicadoObrigatoriedadeBonusObrigatorio"] | components["schemas"]["PredicadoObrigatoriedadeAtendimentoDisponivel"] | components["schemas"]["PredicadoObrigatoriedadeConcorrenciaDuplaObrigatoria"] | components["schemas"]["PredicadoObrigatoriedadeCustomizado"];
        readonly PredicadoObrigatoriedadeAtendimentoDisponivel: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeAtendimentoDisponivel$tipo;
            readonly necessidades: readonly string[];
        };
        readonly PredicadoObrigatoriedadeBonusObrigatorio: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeBonusObrigatorio$tipo;
            readonly modalidadesAplicaveis: readonly string[];
        };
        readonly PredicadoObrigatoriedadeConcorrenciaDuplaObrigatoria: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeConcorrenciaDuplaObrigatoria$tipo;
        };
        readonly PredicadoObrigatoriedadeCustomizado: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeCustomizado$tipo;
            readonly parametros: components["schemas"]["JsonElement"];
        };
        readonly PredicadoObrigatoriedadeDesempateDeveIncluir: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeDesempateDeveIncluir$tipo;
            readonly criterio: string;
        };
        readonly PredicadoObrigatoriedadeDocumentoObrigatorioParaModalidade: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeDocumentoObrigatorioParaModalidade$tipo;
            readonly modalidade: string;
            readonly tipoDocumento: string;
        };
        readonly PredicadoObrigatoriedadeEtapaObrigatoria: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeEtapaObrigatoria$tipo;
            readonly tipoEtapaCodigo: string;
        };
        readonly PredicadoObrigatoriedadeModalidadesMinimas: {
            /** @enum {string} */
            readonly $tipo?: PredicadoObrigatoriedadeModalidadesMinimas$tipo;
            readonly codigos: readonly string[];
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
        readonly UserProfileResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            /** @description CPF (apenas dígitos, sem formatação). PII — sempre mascarar em logs ('***.999.999-**', ADR-0011). */
            readonly cpf: null | string;
            readonly nomeSocial: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly GetAuthenticatedUser: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly GetAuthenticatedUserProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
export enum PathsApiSelecaoObrigatoriedadesLegaisGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum CategoriaObrigatoriedade {
    nenhuma = "nenhuma",
    etapa = "etapa",
    modalidade = "modalidade",
    desempate = "desempate",
    documento = "documento",
    bonus = "bonus",
    atendimento = "atendimento",
    outros = "outros"
}
export enum PredicadoObrigatoriedadeAtendimentoDisponivel$tipo {
    atendimentoDisponivel = "atendimentoDisponivel"
}
export enum PredicadoObrigatoriedadeBonusObrigatorio$tipo {
    bonusObrigatorio = "bonusObrigatorio"
}
export enum PredicadoObrigatoriedadeConcorrenciaDuplaObrigatoria$tipo {
    concorrenciaDuplaObrigatoria = "concorrenciaDuplaObrigatoria"
}
export enum PredicadoObrigatoriedadeCustomizado$tipo {
    customizado = "customizado"
}
export enum PredicadoObrigatoriedadeDesempateDeveIncluir$tipo {
    desempateDeveIncluir = "desempateDeveIncluir"
}
export enum PredicadoObrigatoriedadeDocumentoObrigatorioParaModalidade$tipo {
    documentoObrigatorioParaModalidade = "documentoObrigatorioParaModalidade"
}
export enum PredicadoObrigatoriedadeEtapaObrigatoria$tipo {
    etapaObrigatoria = "etapaObrigatoria"
}
export enum PredicadoObrigatoriedadeModalidadesMinimas$tipo {
    modalidadesMinimas = "modalidadesMinimas"
}
