/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o usuário autenticado
         * @description Retorna informações do usuário extraídas do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUser"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/profile/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Retorna o perfil do usuário autenticado
         * @description Retorna atributos de identidade e institucionais (CPF, NomeSocial) extraídos do access token. Requer autenticação.
         */
        readonly get: operations["GetAuthenticatedUserProfile"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/_smoke/storage/upload": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Smoke E2E — Storage upload
         * @description Faz upload de um arquivo no bucket configurado para validar conectividade + credentials do MinIO. Restrito a usuários com role admin.
         */
        readonly post: operations["smokeStorageUpload"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/_smoke/cache/{key}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Smoke E2E — Cache probe
         * @description Faz SET/GET de uma chave temporária no Redis com TTL 5min para validar conectividade. Restrito a usuários com role admin.
         */
        readonly get: operations["smokeCacheProbe"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/_smoke/messaging/publish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Smoke E2E — Messaging publish
         * @description Publica um SmokePingMessage via Wolverine outbox para validar persistência + transport (PG queue ou Kafka). O handler em Infrastructure.Core registra log do round-trip. Restrito a usuários com role admin.
         */
        readonly post: operations["smokeMessagingPublish"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/campi": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiCampiGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["CampusDto"][];
                        readonly "application/json": readonly components["schemas"]["CampusDto"][];
                        readonly "text/json": readonly components["schemas"]["CampusDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/campi/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["CampusDto"];
                        readonly "application/json": components["schemas"]["CampusDto"];
                        readonly "text/json": components["schemas"]["CampusDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/campi": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarCampusCommand"];
                    readonly "text/json": components["schemas"]["CriarCampusCommand"];
                    readonly "application/*+json": components["schemas"]["CriarCampusCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/campi/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["AtualizarCampusCommand"];
                    readonly "text/json": components["schemas"]["AtualizarCampusCommand"];
                    readonly "application/*+json": components["schemas"]["AtualizarCampusCommand"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/locais-oferta": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiLocaisOfertaGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["LocalOfertaDto"][];
                        readonly "application/json": readonly components["schemas"]["LocalOfertaDto"][];
                        readonly "text/json": readonly components["schemas"]["LocalOfertaDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/locais-oferta/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["LocalOfertaDto"];
                        readonly "application/json": components["schemas"]["LocalOfertaDto"];
                        readonly "text/json": components["schemas"]["LocalOfertaDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/locais-oferta": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarLocalOfertaCommand"];
                    readonly "text/json": components["schemas"]["CriarLocalOfertaCommand"];
                    readonly "application/*+json": components["schemas"]["CriarLocalOfertaCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/locais-oferta/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["AtualizarLocalOfertaCommand"];
                    readonly "text/json": components["schemas"]["AtualizarLocalOfertaCommand"];
                    readonly "application/*+json": components["schemas"]["AtualizarLocalOfertaCommand"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/pesos-area-enem": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiPesosAreaEnemGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["PesoAreaEnemDto"][];
                        readonly "application/json": readonly components["schemas"]["PesoAreaEnemDto"][];
                        readonly "text/json": readonly components["schemas"]["PesoAreaEnemDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/pesos-area-enem/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["PesoAreaEnemDto"];
                        readonly "application/json": components["schemas"]["PesoAreaEnemDto"];
                        readonly "text/json": components["schemas"]["PesoAreaEnemDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/pesos-area-enem": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarPesoAreaEnemCommand"];
                    readonly "text/json": components["schemas"]["CriarPesoAreaEnemCommand"];
                    readonly "application/*+json": components["schemas"]["CriarPesoAreaEnemCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/pesos-area-enem/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["AtualizarPesoAreaEnemCommand"];
                    readonly "text/json": components["schemas"]["AtualizarPesoAreaEnemCommand"];
                    readonly "application/*+json": components["schemas"]["AtualizarPesoAreaEnemCommand"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/referencias-reserva-demografica": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Cursor opaco AES-GCM emitido pelo servidor no header Link da página anterior. Ausente na primeira página. Cliente trata como string opaca — não decodificar (ADR-0026, ADR-0031). */
                    readonly cursor?: string;
                    /** @description Tamanho máximo da janela de resultados. Limites configurados em CursorPaginationOptions; valores fora do range retornam 422 com code uniplus.pagination.limit_invalido (ADR-0026). */
                    readonly limit?: number;
                    /** @description Direção de navegação keyset (ADR-0089): 'next' (default) avança, 'prev' retrocede. Normalmente o cliente apenas segue o cursor opaco do rel="prev"/rel="next" do header Link — que já inclui o direction correto. */
                    readonly direction?: PathsApiReferenciasReservaDemograficaGetParametersQueryDirection;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description Links de navegação da paginação (RFC 5988/8288). rel="self" sempre presente; rel="prev"/rel="next" quando há página anterior/próxima (ADR-0089). Cada link carrega o cursor opaco no parâmetro `cursor` e o `direction` correspondente (ADR-0026). */
                        readonly Link?: string;
                        /** @description Quantidade de itens retornados na página atual (sempre menor ou igual ao limit efetivo). */
                        readonly "X-Page-Size"?: number;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": readonly components["schemas"]["ReferenciaReservaDemograficaDto"][];
                        readonly "application/json": readonly components["schemas"]["ReferenciaReservaDemograficaDto"][];
                        readonly "text/json": readonly components["schemas"]["ReferenciaReservaDemograficaDto"][];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/referencias-reserva-demografica/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": components["schemas"]["ReferenciaReservaDemograficaDto"];
                        readonly "application/json": components["schemas"]["ReferenciaReservaDemograficaDto"];
                        readonly "text/json": components["schemas"]["ReferenciaReservaDemograficaDto"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Acceptable */
                readonly 406: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/referencias-reserva-demografica": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["CriarReferenciaReservaDemograficaCommand"];
                    readonly "text/json": components["schemas"]["CriarReferenciaReservaDemograficaCommand"];
                    readonly "application/*+json": components["schemas"]["CriarReferenciaReservaDemograficaCommand"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "text/plain": string;
                        readonly "application/json": string;
                        readonly "text/json": string;
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/referencias-reserva-demografica/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header: {
                    /** @description Chave opaca (1-255 ASCII printable, sem ',' ou ';') para retry seguro do comando. Replay com mesma key + mesmo body retorna response cacheada (ADR-0027). */
                    readonly "Idempotency-Key": string;
                };
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["AtualizarReferenciaReservaDemograficaCommand"];
                    readonly "text/json": components["schemas"]["AtualizarReferenciaReservaDemograficaCommand"];
                    readonly "application/*+json": components["schemas"]["AtualizarReferenciaReservaDemograficaCommand"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unprocessable Entity */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AtualizarCampusCommand: {
            /** Format: uuid */
            readonly id: string;
            readonly sigla: string;
            readonly nome: string;
            readonly cidadeCodigoIbge: string;
            readonly cidadeNome: string;
            readonly cidadeUf: string;
            readonly endereco: null | components["schemas"]["EnderecoGeoInput"];
            readonly codigoEmec: null | string;
        };
        readonly AtualizarLocalOfertaCommand: {
            /** Format: uuid */
            readonly id: string;
            readonly tipo: components["schemas"]["TipoLocalOferta"];
            /** Format: uuid */
            readonly campusResponsavelId: null | string;
            readonly cidadeCodigoIbge: string;
            readonly cidadeNome: string;
            readonly cidadeUf: string;
            readonly endereco: null | components["schemas"]["EnderecoGeoInput"];
            readonly codigoEmec: null | string;
        };
        readonly AtualizarPesoAreaEnemCommand: {
            /** Format: uuid */
            readonly id: string;
            /** Format: double */
            readonly pesoRedacao: number | string;
            /** Format: double */
            readonly pesoCienciasNatureza: number | string;
            /** Format: double */
            readonly pesoCienciasHumanas: number | string;
            /** Format: double */
            readonly pesoLinguagens: number | string;
            /** Format: double */
            readonly pesoMatematica: number | string;
            /** Format: double */
            readonly corteRedacao: number | string;
            readonly baseLegal: string;
        };
        readonly AtualizarReferenciaReservaDemograficaCommand: {
            /** Format: uuid */
            readonly id: string;
            readonly censoReferencia: string;
            /** Format: double */
            readonly ppiPercentual: number | string;
            /** Format: double */
            readonly quilombolaPercentual: number | string;
            /** Format: double */
            readonly pcdPercentual: number | string;
            readonly baseLegal: string;
        };
        readonly AuthenticatedUserResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
        readonly CampusDto: {
            /** Format: uuid */
            readonly id: string;
            readonly sigla: string;
            readonly nome: string;
            readonly cidade: components["schemas"]["CidadeReferenciaDto"];
            readonly endereco: null | components["schemas"]["EnderecoGeoDto"];
            readonly codigoEmec: null | string;
            /** Format: date-time */
            readonly criadoEm: string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly CidadeReferenciaDto: {
            readonly codigoIbge: string;
            readonly nome: string;
            readonly uf: string;
            readonly origem?: null | string;
            /** Format: date-time */
            readonly displayAtualizadoEm?: null | string;
        };
        readonly CidadeReferenciaInput: {
            readonly codigoIbge: null | string;
            readonly nome: null | string;
            readonly uf: null | string;
        };
        readonly CriarCampusCommand: {
            readonly sigla: string;
            readonly nome: string;
            readonly cidadeCodigoIbge: string;
            readonly cidadeNome: string;
            readonly cidadeUf: string;
            readonly endereco: null | components["schemas"]["EnderecoGeoInput"];
            readonly codigoEmec: null | string;
        };
        readonly CriarLocalOfertaCommand: {
            readonly tipo: components["schemas"]["TipoLocalOferta"];
            /** Format: uuid */
            readonly campusResponsavelId: null | string;
            readonly cidadeCodigoIbge: string;
            readonly cidadeNome: string;
            readonly cidadeUf: string;
            readonly endereco: null | components["schemas"]["EnderecoGeoInput"];
            readonly codigoEmec: null | string;
        };
        readonly CriarPesoAreaEnemCommand: {
            readonly resolucao: string;
            readonly grupoCurso: string;
            /** Format: double */
            readonly pesoRedacao: number | string;
            /** Format: double */
            readonly pesoCienciasNatureza: number | string;
            /** Format: double */
            readonly pesoCienciasHumanas: number | string;
            /** Format: double */
            readonly pesoLinguagens: number | string;
            /** Format: double */
            readonly pesoMatematica: number | string;
            readonly baseLegal: string;
            /** Format: double */
            readonly corteRedacao?: null | number | string;
        };
        readonly CriarReferenciaReservaDemograficaCommand: {
            readonly censoReferencia: string;
            /** Format: double */
            readonly ppiPercentual: number | string;
            /** Format: double */
            readonly quilombolaPercentual: number | string;
            /** Format: double */
            readonly pcdPercentual: number | string;
            readonly baseLegal: string;
        };
        readonly EnderecoGeoDto: {
            readonly cep: string;
            readonly logradouro: null | string;
            readonly numero: null | string;
            readonly complemento: null | string;
            readonly bairro: null | string;
            readonly distrito: null | string;
            readonly cidade: components["schemas"]["CidadeReferenciaDto"];
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly nivelResolucao: string;
            readonly origem: string;
            /** Format: date-time */
            readonly displayAtualizadoEm: null | string;
        };
        readonly EnderecoGeoInput: {
            readonly cep: null | string;
            readonly logradouro: null | string;
            readonly numero: null | string;
            readonly complemento: null | string;
            readonly bairro: null | string;
            readonly distrito: null | string;
            readonly cidade: null | components["schemas"]["CidadeReferenciaInput"];
            /** Format: double */
            readonly latitude: null | number | string;
            /** Format: double */
            readonly longitude: null | number | string;
            readonly nivelResolucao: null | string;
            readonly origem: null | string;
        };
        /** Format: binary */
        readonly IFormFile: string;
        readonly LocalOfertaDto: {
            /** Format: uuid */
            readonly id: string;
            readonly tipo: components["schemas"]["TipoLocalOferta"];
            /** Format: uuid */
            readonly campusResponsavelId: null | string;
            readonly cidade: components["schemas"]["CidadeReferenciaDto"];
            readonly endereco: null | components["schemas"]["EnderecoGeoDto"];
            readonly codigoEmec: null | string;
            /** Format: date-time */
            readonly criadoEm: string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly PesoAreaEnemDto: {
            /** Format: uuid */
            readonly id: string;
            readonly resolucao: string;
            readonly grupoCurso: string;
            /** Format: double */
            readonly pesoRedacao: number | string;
            /** Format: double */
            readonly pesoCienciasNatureza: number | string;
            /** Format: double */
            readonly pesoCienciasHumanas: number | string;
            /** Format: double */
            readonly pesoLinguagens: number | string;
            /** Format: double */
            readonly pesoMatematica: number | string;
            /** Format: double */
            readonly corteRedacao: number | string;
            readonly baseLegal: string;
            /** Format: date-time */
            readonly criadoEm: string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        readonly ProblemDetails: {
            readonly type?: null | string;
            readonly title?: null | string;
            /** Format: int32 */
            readonly status?: null | number | string;
            readonly detail?: null | string;
            readonly instance?: null | string;
        };
        readonly ReferenciaReservaDemograficaDto: {
            /** Format: uuid */
            readonly id: string;
            readonly censoReferencia: string;
            /** Format: double */
            readonly ppiPercentual: number | string;
            /** Format: double */
            readonly quilombolaPercentual: number | string;
            /** Format: double */
            readonly pcdPercentual: number | string;
            readonly baseLegal: string;
            /** Format: date-time */
            readonly criadoEm: string;
            readonly _links?: null | {
                readonly [key: string]: string;
            };
        };
        /** @enum {string} */
        readonly TipoLocalOferta: TipoLocalOferta;
        readonly UserProfileResponse: {
            readonly userId: null | string;
            readonly name: null | string;
            readonly email: null | string;
            /** @description CPF (apenas dígitos, sem formatação). PII — sempre mascarar em logs ('***.999.999-**', ADR-0011). */
            readonly cpf: null | string;
            readonly nomeSocial: null | string;
            readonly roles: readonly string[];
            /** Format: date-time */
            readonly timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly GetAuthenticatedUser: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly GetAuthenticatedUserProfile: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Unauthorized */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly smokeStorageUpload: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": {
                    readonly file: components["schemas"]["IFormFile"];
                };
            };
        };
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly smokeCacheProbe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly key: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly smokeMessagingPublish: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description OK */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum PathsApiCampiGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiLocaisOfertaGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiPesosAreaEnemGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum PathsApiReferenciasReservaDemograficaGetParametersQueryDirection {
    next = "next",
    prev = "prev"
}
export enum TipoLocalOferta {
    nenhum = "nenhum",
    campusSede = "campusSede",
    campusForaDeSede = "campusForaDeSede",
    cursoForaDeSede = "cursoForaDeSede",
    poloEad = "poloEad",
    convenioInteriorizacao = "convenioInteriorizacao",
    outro = "outro"
}
